### ISSUE TITLE
Training Code

### ISSUE THREAD

**Issue by zhu2014yi** [zhanght021/RPT#10]
您好，我对您的代码挺感兴趣的，请问大概啥时候能开源训练部分代码呢？

**Comment by zhanght021** [comment]
现在公司已经放假了，上班之后就尽量会早点来源的，其实可以参考reppoints，包括正负样本设置几乎一样@zhu2014yi

**Comment by zhu2014yi** [comment]
好的，非常感谢

> 现在公司已经放假了，上班之后就尽量会早点来源的，其实可以参考reppoints，包括正负样本设置几乎一样@zhu2014yi
