### ISSUE TITLE
code problems

### ISSUE THREAD

**Issue by xin858466707** [zhanght021/RPT#16]
hi Ziang !
很棒的工作！请问您训练部分的代码什么时候开源呢？

**Comment by zhanght021** [comment]
hi，其中训练代码真的真的很简单，标签设置啥的都只需要参考reppoints的代码就好了，代码其实都是从reppoints中剥的，然后和pysot的代码结合一下就好了。因为最近公司最近一直比较忙，还有就是我们暂时没有做这个方向了，所以一直没有时间整理
