### ISSUE TITLE
VOT2020数据集json文件获取

### ISSUE THREAD

**Issue by sysu-shey** [zhanght021/RPT#8]
您好！请问您怎么获取VOT2020.json文件，方便共享么？我只能获取description.json文件 @zhanght021

**Comment by zhanght021** [comment]
vot2020还是推荐用vot官方工具，那个不需要json文件，当时我为了在pysot中测试vot2020，写过一个脚本，但是也只是能输出结果,EAO我还是得用官方工具去计算

**Comment by sysu-shey** [comment]
因为要使用pysot工具中的tune.py文件（稍微）调下参，没有json工具好像不是很方便，请问您怎么处理呀 @zhanght021

**Comment by zhanght021** [comment]
参加vot2020的比赛我们没用tune.py来调参数，完全是手动看感觉调的，因为加上在线分类器之后鲁棒性会好很多，不太需要疯狂的搜参数来增加性能@sysu-shey

**Comment by sysu-shey** [comment]
好哒！谢谢大佬！ @zhanght021
